### ISSUE TITLE
Scraper is failing

### ISSUE THREAD

**Issue by spa5k** [epctex/bbb-scraper#1]
```
2023-10-13T08:20:16.556Z ACTOR: Pulling Docker image of build 4gQONMNbRsuwn78Lk from repository.
2023-10-13T08:20:17.976Z ACTOR: Creating Docker container.
2023-10-13T08:20:18.144Z ACTOR: Starting Docker container.
2023-10-13T08:20:21.228Z INFO  System info {"apifyVersion":"3.1.11","apifyClientVersion":"2.8.0","crawleeVersion":"3.5.7","osType":"Linux","nodeVersion":"v18.18.0"}
2023-10-13T08:20:21.233Z INFO  PHASE -- STARTING ACTOR.
2023-10-13T08:20:21.342Z INFO  Search mode will be only available when Location, Country and Search fields are filled
2023-10-13T08:20:21.491Z INFO  PHASE -- SETTING UP CRAWLER.
2023-10-13T08:20:21.854Z INFO  CRAWLER STARTED.
2023-10-13T08:20:22.432Z INFO  PlaywrightCrawler: Starting the crawler.
2023-10-13T08:20:23.890Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:20:23.893Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":1}
2023-10-13T08:20:38.076Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:20:38.078Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":2}
2023-10-13T08:20:44.225Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:20:44.228Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":3}
2023-10-13T08:20:54.087Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:20:54.089Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":4}
2023-10-13T08:20:58.966Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:20:58.969Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":5}
2023-10-13T08:21:04.399Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:21:04.402Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":6}
2023-10-13T08:21:17.755Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:21:17.757Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":7}
2023-10-13T08:21:22.431Z INFO  Statistics: PlaywrightCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":0,"requestTotalDurationMillis":0,"requestsTotal":0,"crawlerRuntimeMillis":60577,"retryHistogram":[]}
2023-10-13T08:21:22.453Z INFO  PlaywrightCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}
2023-10-13T08:21:25.224Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:21:25.227Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":8}
2023-10-13T08:21:30.238Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:21:30.241Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":9}
2023-10-13T08:21:36.290Z WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. Request blocked - received 403 status code.
2023-10-13T08:21:36.292Z  {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","retryCount":10}
2023-10-13T08:21:42.400Z ERROR PlaywrightCrawler: Request failed and reached maximum retries. Error: Request blocked - received 403 status code.
2023-10-13T08:21:42.402Z     at PlaywrightCrawler._throwOnBlockedRequest (/home/myuser/node_modules/@crawlee/basic/internals/basic-crawler.js:653:19)
2023-10-13T08:21:42.405Z     at PlaywrightCrawler._responseHandler (/home/myuser/node_modules/@crawlee/browser/internals/browser-crawler.js:352:22)
2023-10-13T08:21:42.407Z     at PlaywrightCrawler._runRequestHandler (/home/myuser/node_modules/@crawlee/browser/internals/browser-crawler.js:238:24)
2023-10-13T08:21:42.409Z     at async PlaywrightCrawler._runRequestHandler (/home/myuser/node_modules/@crawlee/playwright/internals/playwright-crawler.js:109:9)
2023-10-13T08:21:42.412Z     at async wrap (/home/myuser/node_modules/@apify/timeout/index.js:52:21) {"id":"AqVSKT7706sbfYW","url":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details","method":"GET","uniqueKey":"https://www.bbb.org/us/co/englewood/profile/medical-equipment/zynex-medical-inc-1296-57000503/customer-reviews/details"}
2023-10-13T08:21:42.462Z INFO  PlaywrightCrawler: All requests from the queue have been processed, the crawler will shut down.
2023-10-13T08:21:42.723Z INFO  PlaywrightCrawler: Final request statistics: {"requestsFinished":0,"requestsFailed":1,"retryHistogram":[null,null,null,null,null,null,null,null,null,null,1],"requestAvgFailedDurationMillis":2596,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":0,"requestTotalDurationMillis":2596,"requestsTotal":1,"crawlerRuntimeMillis":80868}
2023-10-13T08:21:42.725Z INFO  PlaywrightCrawler: Error analysis: {"totalErrors":1,"uniqueErrors":1,"mostCommonErrors":["1x: Request blocked - received 403 status code. (/home/myuser/node_modules/@crawlee/basic/internals/basic-crawler.js:653:19)"]}
2023-10-13T08:21:42.728Z INFO  PlaywrightCrawler: Finished! Total 1 requests: 0 succeeded, 1 failed. {"terminal":true}

```
Cloudflare was recently added to BBB and we were looking for solution to pass through it, can the scraper be updated to handle it?

**Comment by tugkan** [comment]
Hey @spa5k !

Thank you very much for reaching out. I just wanted to let you know that I already passed this information to the Engineering Team where they are actively working on this issue. Once it is done, I will let you know.

Please let me know if there is anything that I can assist you with,
Best.

**Comment by spa5k** [comment]
Yep one more thing, is there a way to only scrape the reviews for bbb, since we don't really need any other info other than them.

**Comment by tugkan** [comment]
Hey @spa5k ! The new version of the BBB actor has been deployed. It is still getting errors occasionally but we think that this problem is being occurred due to the downtime that BBB is facing with currently. Whenever it is done on their side, all should work well.

Please let me know if there is anything that I can assist you with.
Best
